version: '3.8'
services:
  app:
    build: ./docker/php
    container_name: laravel-app
    volumes:
      - ./src:/var/www
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: nginx-web
    volumes:
      - ./src/public:/var/www/public
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

volumes:
  dbdata:
  redisdata:
  mongodata:

networks:
  app-network:
    driver: bridge
